### ISSUE TITLE
Failed to run generate_custom_image.py

### ISSUE THREAD

**Issue by functicons** [GoogleCloudPlatform/cloud-dataproc#101]
I was following [Create a Cloud Dataproc Custom Image](https://cloud.google.com/dataproc/docs/guides/dataproc-images) to run generate_custom_image.py downloaded from [here](https://github.com/GoogleCloudPlatform/cloud-dataproc/blob/master/custom-images/generate_custom_image.py):

I was in a Miniconda Python 2.7 environment, first it said:

```
ImportError: No module named constants
```

then I installed constants-0.6.0, but when running the script:

```
$ python2.7 generate_custom_image.py     --image-name my-ubuntu-image     --dataproc-version 1.4.5-ubuntu18     --customization-script my-script.sh     --daisy-path ${HOME}/opt/daisy/daisy     --zone us-west1-a     --gcs-bucket gs://my-bucket
```

the following error happened 

```
Traceback (most recent call last):
  File "generate_custom_image.py", line 539, in <module>
    run()
  File "generate_custom_image.py", line 332, in run
    help=constants.version_help_text)
AttributeError: 'module' object has no attribute 'version_help_text'
```

**Comment by functicons** [comment]
Turns out, the [doc](https://cloud.google.com/dataproc/docs/guides/dataproc-images) is not accurate, it just says download the generate_custom_image.py, but actually need to clone the whole repo and run the script in the repo, as it has local dependencies on [constants.py](https://github.com/GoogleCloudPlatform/cloud-dataproc/blob/master/custom-images/constants.py).

**Comment by functicons** [comment]
The problem above was actually that, my custom script `--customization-script my-script.sh` doesn't exist. The error was confusing.

**Comment by functicons** [comment]
I ended up with running the script inside a GCE VM, the custom script is a simple hello world.

```
$ cat ~/tmp/my-script.sh
#!/bin/bash

echo "Hello World!"
```

but it failed:

```
$ python2.7 generate_custom_image.py     --image-name my-ubuntu-image     --dataproc-version 1.4.5-ubuntu18     --customization-script ~/tmp/my-script.sh     --daisy-path ~/opt/daisy/dais
y     --zone us-west1-a     --gcs-bucket gs://my-bucket

...
NFO:__main__:Getting Dataproc base image name...
INFO:__main__:Returned Dataproc base image: projects/cloud-dataproc/global/images/dataproc-1-4-ubu18-20190510-000000-rc01
INFO:__main__:Created Daisy workflow...
INFO:__main__:Successfully created Daisy workflow...
INFO:__main__:Creating custom image with Daisy workflow...
[Daisy] Running workflow "my-ubuntu-image" (id=m8zty)
[my-ubuntu-image]: 2019-06-03T20:16:14Z Validating workflow
[my-ubuntu-image]: 2019-06-03T20:16:14Z Validating step "create-disks"
[my-ubuntu-image]: 2019-06-03T20:16:15Z Validating step "create-inst-install"
[my-ubuntu-image]: 2019-06-03T20:16:15Z Validating step "wait-for-inst-install"
[my-ubuntu-image]: 2019-06-03T20:16:15Z Validating step "wait-for-inst-shutdown"
[my-ubuntu-image]: 2019-06-03T20:16:15Z Validating step "create-image"
[my-ubuntu-image]: 2019-06-03T20:16:15Z Validating step "delete-inst-install"
[my-ubuntu-image]: 2019-06-03T20:16:15Z Validation Complete
[my-ubuntu-image]: 2019-06-03T20:16:15Z Workflow Project: google.com:dagang-devconsole
[my-ubuntu-image]: 2019-06-03T20:16:15Z Workflow Zone: us-west1-a
[my-ubuntu-image]: 2019-06-03T20:16:15Z Workflow GCSPath: gs://xxx
[my-ubuntu-image]: 2019-06-03T20:16:15Z Daisy scratch path: https://console.cloud.google.com/storage/browser/xxx/daisy-my-ubuntu-image-20190603-20:16:14-m8zty
[my-ubuntu-image]: 2019-06-03T20:16:15Z Uploading sources
[my-ubuntu-image]: 2019-06-03T20:16:16Z Running workflow
[my-ubuntu-image]: 2019-06-03T20:16:16Z Running step "create-disks" (CreateDisks)
[my-ubuntu-image.create-disks]: 2019-06-03T20:16:16Z CreateDisks: Creating disk "my-ubuntu-image-install-my-ubuntu-image-m8zty".
[my-ubuntu-image]: 2019-06-03T20:18:05Z Step "create-disks" (CreateDisks) successfully finished.
[my-ubuntu-image]: 2019-06-03T20:18:05Z Running step "create-inst-install" (CreateInstances)
[my-ubuntu-image.create-inst-install]: 2019-06-03T20:18:05Z CreateInstances: Creating instance "my-ubuntu-image-install-my-ubuntu-image-m8zty".
[my-ubuntu-image]: 2019-06-03T20:18:17Z Step "create-inst-install" (CreateInstances) successfully finished.
[my-ubuntu-image]: 2019-06-03T20:18:17Z Running step "wait-for-inst-install" (WaitForInstancesSignal)
[my-ubuntu-image.create-inst-install]: 2019-06-03T20:18:17Z CreateInstances: Streaming instance "my-ubuntu-image-install-my-ubuntu-image-m8zty" serial port 1 output to https://storage.cloud.google.com/xxx/daisy-my-ubuntu-image-20190603-20:16:14-m8zty/logs/my-ubuntu-image-install-my-ubuntu-image-m8zty-serial-port1.log
[my-ubuntu-image.wait-for-inst-install]: 2019-06-03T20:18:17Z WaitForInstancesSignal: Instance "my-ubuntu-image-install-my-ubuntu-image-m8zty": watching serial port 1, SuccessMatch: "BuildSucceeded:", FailureMatch: "BuildFailed:".
[my-ubuntu-image]: 2019-06-03T20:18:58Z Error running workflow: step "wait-for-inst-install" run error: WaitForInstancesSignal FailureMatch found for "my-ubuntu-image-install-my-ubuntu-image-m8zty": "BuildFailed: Dataproc Initialization Actions Failed. Please check your initialization script."

Traceback (most recent call last):
  File "generate_custom_image.py", line 539, in <module>
    run()
  File "generate_custom_image.py", line 511, in run
    run_daisy(os.path.abspath(args.daisy_path), workflow)
  File "generate_custom_image.py", line 166, in run_daisy
    raise RuntimeError("Error building custom image.")
RuntimeError: Error building custom image.
```
