### ISSUE TITLE
[custom images] Smoke testing fail on ould not find required format '([^-]*)-([^-]*)-([^-]*)$' for Dataproc version on image

### ISSUE THREAD

**Issue by howie** [GoogleCloudPlatform/cloud-dataproc#72]
It seems the version regex on generate_custom_image.py not the same as gcp API ?
In generate_custom_image.py  Regex = r"^\d+\.\d+\.\d+(-.{4})?$" 

I can create a custom image , but can't use it to create cluster when running smoke test.
The  following is error message

```
.
. (skip )
.
[Daisy] Workflow "pyspark-with-conda-v2" finished
[Daisy] All workflows completed successfully.
INFO:__main__:Successfully created custom image with Daisy workflow...
INFO:__main__:Setting label on custom image...
Updating labels of image [pyspark-with-conda-v2]...done.
INFO:__main__:Successfully set label on custom image...
INFO:__main__:Verifying the custom image...
INFO:__main__:Creating Dataproc workflow-template verify-image-20180827174046-4575d375 with image pyspark-with-conda-v2...
createTime: '2018-08-27T09:40:47.458Z'
id: verify-image-20180827174046-4575d375
jobs:
- sparkJob:
    args:
    - '1000'
    jarFileUris:
    - file:///usr/lib/spark/examples/jars/spark-examples.jar
    mainClass: org.apache.spark.examples.SparkPi
  stepId: '001'
name: projects/pvmax-155104/regions/global/workflowTemplates/verify-image-20180827174046-4575d375
placement:
  managedCluster:
    clusterName: verify-image-20180827174046-4575d375
    config:
      gceClusterConfig:
        zoneUri: asia-east1-b
      masterConfig:
        imageUri: https://www.googleapis.com/compute/beta/projects/pvmax-155104/global/images/pyspark-with-conda-v2
      workerConfig:
        imageUri: https://www.googleapis.com/compute/beta/projects/pvmax-155104/global/images/pyspark-with-conda-v2
updateTime: '2018-08-27T09:40:51.449Z'
version: 3
INFO:__main__:Successfully created Dataproc workflow-template verify-image-20180827174046-4575d375 with image pyspark-with-conda-v2...
INFO:__main__:Smoke testing Dataproc workflow-template %s...
Waiting on operation [projects/pvmax-155104/regions/global/operations/3b8cc97b-21b7-46f8-a64f-956248cd38b6].
WorkflowTemplate [verify-image-20180827174046-4575d375] PENDING
WorkflowTemplate [verify-image-20180827174046-4575d375] DONE
**Could not find required format '([^-]*)-([^-]*)-([^-]*)$' for Dataproc version on image 'https://www.googleapis.com/compute/beta/projects/pvmax-155104/global/images/pyspark-with-conda-v2'.
ERROR: (gcloud.beta.dataproc.workflow-templates.instantiate) Operation [projects/pvmax-155104/regions/global/operations/3b8cc97b-21b7-46f8-a64f-956248cd38b6] failed: Error submitting create cluster request.
ERROR:__main__:Verification of custom image pyspark-with-conda-v2 failed: Unable to instantiate workflow template.**
INFO:__main__:Deleting Dataproc workflow-template verify-image-20180827174046-4575d375...
INFO:__main__:Successfully deleted Dataproc workflow-template verify-image-20180827174046-4575d375...
Traceback (most recent call last):
  File "generate_custom_image.py", line 254, in verify_custom_image
    _instantiate_workflow_template(workflow_name, project_id)
  File "generate_custom_image.py", line 224, in _instantiate_workflow_template
    raise RuntimeError("Unable to instantiate workflow template.")
RuntimeError: Unable to instantiate workflow template.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate_custom_image.py", line 466, in <module>
    run()
  File "generate_custom_image.py", line 450, in run
    verify_custom_image(args.image_name, project_id, args.zone, args.subnetwork)
  File "generate_custom_image.py", line 260, in verify_custom_image
    raise RuntimeError(err_msg)
RuntimeError: Verification of custom image pyspark-with-conda-v2 failed: Unable to instantiate workflow template.
```

**Comment by takeon8** [comment]
hi @howie, sorry for the issue here. Can you please pull the latest code from this repo and try again?

**Comment by howie** [comment]
It works ! thanks ~:)
